name: Boomi CI/CD (Dynamic)

on:
  push:
    paths:
      - 'config/deployment.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Read deployment config
        run: |
          COMPONENT_ID=$(jq -r '.componentId' config/deployment.json)
          ENV_NAME=$(jq -r '.environment' config/deployment.json)

          echo "BOOMI_COMPONENT_ID=$COMPONENT_ID" >> $GITHUB_ENV
          echo "ENV_NAME=$ENV_NAME" >> $GITHUB_ENV

      - name: Set Environment ID
        run: |
          if [ "$ENV_NAME" = "dev" ]; then
            echo "BOOMI_ENVIRONMENT_ID=${{ secrets.DEV_ENV_ID }}" >> $GITHUB_ENV
         
          elif [ "$ENV_NAME" = "prod" ]; then
            echo "BOOMI_ENVIRONMENT_ID=${{ secrets.PROD_ENV_ID }}" >> $GITHUB_ENV
          else
            echo "Invalid environment"
            exit 1
          fi

      - name: Give execute permission
        run: chmod +x scripts/deploy.sh

      - name: Run Deployment Script
        run: bash scripts/deploy.sh
        env:
          BOOMI_ACCOUNT_ID: ${{ secrets.BOOMI_ACCOUNT_ID }}
          BOOMI_USERNAME: ${{ secrets.BOOMI_USERNAME }}
          BOOMI_PASSWORD: ${{ secrets.BOOMI_PASSWORD }}
          BOOMI_COMPONENT_ID: ${{ env.BOOMI_COMPONENT_ID }}
          BOOMI_ENVIRONMENT_ID: ${{ env.BOOMI_ENVIRONMENT_ID }}
